Array manipulation 2 - Viviane V.
vivianevieira/c1020-code-solutions pull request #54
Opened 2020-10-24 20:35 UTC by vivianevieira

![Screen Shot 2020-10-24 at 1 32 50 PM](https://user-images.githubusercontent.com/71540857/97093033-b99e4a80-15fd-11eb-997a-282f24aeed9e.png)
![Screen Shot 2020-10-24 at 1 32 55 PM](https://user-images.githubusercontent.com/71540857/97093035-bb680e00-15fd-11eb-91a4-0131393be2cc.png)

2020-11-07 00:09 UTC, uzair-ashraf requested changes

2020-11-07 00:09 UTC, uzair-ashraf commented on array-manipulation-2/src/drop-right.js
> +  }
This mutates the original array and accomplishes the task in an incorrect way.  You want to use a loop and do you best to not modify the original array.

2020-11-07 00:09 UTC, uzair-ashraf commented on array-manipulation-2/src/take.js
> +    array.length = count;
This mutates the original array, and should return a new array.  You should use a loop in here.

2020-11-16 23:26 UTC, thebearingedge approved these changes

2020-11-16 23:27 UTC, merged